# -*- coding: utf-8 -*-
"""ai learning buddy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhw-OetCl1JwAfUc_UwYQWdsvDAecH7b
"""

!pip install -q streamlit pyngrok google-generativeai

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import google.generativeai as genai
# 
# # -----------------------------
# # Gemini Configuration
# # -----------------------------
# genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
# 
# model = genai.GenerativeModel("gemini-2.5-flash")
# 
# # -----------------------------
# # Page Config
# # -----------------------------
# st.set_page_config(
#     page_title="AI Learning Buddy",
#     page_icon="🎓",
#     layout="wide"
# )
# 
# st.title("🎓 AI Learning Buddy")
# 
# 
# # -----------------------------
# # Session State
# # -----------------------------
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# 
# # Stores all previous chats
# if "saved_chats" not in st.session_state:
#     st.session_state.saved_chats = []
# 
# # -----------------------------
# # Sidebar
# # -----------------------------
# with st.sidebar:
# 
#     st.title("💬 Chat History")
# 
#     if st.button("➕ New Chat"):
#       if len(st.session_state.messages) > 0:
#         first_question = "New Chat"
# 
#         for msg in st.session_state.messages:
#           if msg["role"] == "user":
#             title_prompt = f"""
# Generate a very short chat title (3 to 5 words only)
# for this conversation.
# User message:
# {msg['content']}
# 
# Return ONLY the title.
# """
# 
#             try:
#               title_response = model.generate_content(title_prompt)
#               first_question = title_response.text.strip()
#             except:
#               first_question = msg["content"][:30]
# 
#             break
# 
# 
# 
#         # Save only if it is not already saved
#         already_exists = False
# 
#         for chat in st.session_state.saved_chats:
#           if chat["messages"] == st.session_state.messages:
#             already_exists = True
#             break
#         if not already_exists:
#           st.session_state.saved_chats.append({
#             "title": first_question,
#             "messages": st.session_state.messages.copy()
#         })
# 
#         # Start fresh chat
#         st.session_state.messages = []
# 
#         st.rerun()
# 
#     st.markdown("---")
# 
#     if len(st.session_state.saved_chats) == 0:
#         st.info("No previous chats")
# 
#     else:
#       for i, chat in enumerate(reversed(st.session_state.saved_chats)):
# 
#         if st.button("📝 " + chat["title"], key=f"chat_{i}"):
# 
#             st.session_state.messages = chat["messages"]
# 
#             st.rerun()
# 
#     st.markdown("---")
# 
# 
# # -----------------------------
# # Display Chat
# # -----------------------------
# for message in st.session_state.messages:
#     with st.chat_message(message["role"]):
#         st.markdown(message["content"])
# 
# # -----------------------------
# # Chat Input
# # -----------------------------
# prompt = st.chat_input("Ask me anything...")
# 
# if prompt:
# 
#     # Show user message
#     st.session_state.messages.append(
#         {
#             "role": "user",
#             "content": prompt
#         }
#     )
# 
#     with st.chat_message("user"):
#         st.markdown(prompt)
# 
#     # Gemini Response
#     with st.chat_message("assistant"):
# 
#         with st.spinner("Thinking..."):
# 
#             response = model.generate_content(prompt)
# 
#             answer = response.text
# 
#             st.markdown(answer)
# 
#     # Save assistant response
#     st.session_state.messages.append(
#         {
#             "role": "assistant",
#             "content": answer
#         }
#     )
# 
#     # Save prompt in sidebar
# 
# 
#     st.rerun()

!nohup streamlit run app.py --server.port 8501 &

import time
time.sleep(10)

!cat nohup.out

!pip install -q pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("3GFtRuOCxpxMGLvhBxtjECjBWcE_M58Z9rSCVjbuPJf2TmhU")

public_url = ngrok.connect(8501)

print(public_url)

!pkill -f streamlit

!nohup streamlit run app.py --server.port 8501 &

import time
time.sleep(10)

!cat nohup.out

from pyngrok import ngrok

public_url = ngrok.connect(8501)

print(public_url)